### ISSUE TITLE
Can intent filter work in custom tabs?

### ISSUE THREAD

**Issue by r511253** [GoogleChrome/custom-tabs-client#15]
Use the same link, my intent filter can't work at custom tabs but works at chrome.
Do custom tabs support intent filter?
sincerely

**Comment by pasko** [comment]
please file bugs using the link at the bottom of readme

also please provide more details/code what you are trying to do and what does not work

**Comment by b95505017** [comment]
Same here, not sure it's a bug or not.
For example, I declare an intent-filter below.
````xml
            <intent-filter>
                <action android:name="android.intent.action.VIEW" />

                <category android:name="android.intent.category.DEFAULT" />
                <category android:name="android.intent.category.BROWSABLE" />
                <data
                    android:host="example.com"
                    android:scheme="https" />
            </intent-filter>
````
When click the scheme+host link in Chrome app, my app could receive the intent, a system intent chooser will show up for asking me next behavior, but not with custom tabs. Not sure it's a normal behavior or not.
In WebView, we could control the url handling behavior via WebChromeClient.

**Comment by r511253** [comment]
For example, I install both facebook app and chrome app on my phone.
When I click this link in facebook "https://www.facebook.com/juksymag/videos/10153239052963937/?__mref=message_bubble" via chrome, system intent chooser will show up and let me choose open the link by facebook or by chrome. But when I click the same facebook link via custom tabs, system intent chooser won't show up and just open the link by custom tabs.

**Comment by jollycopper** [comment]
Custom tab's current intent policy is:
1. If the user has previously selected a default external app to handle a type of url, then we respect the users' choice and send the url to the app. (By saying default I mean the user once selected an app as the default handler in an intent picker before, or In M+ the app is verified by the OS that it owns a url).
2. If the url has a custom scheme that chrome is not capable to handle (such as market://), chrome will always fire an intent.
3. Otherwise custom tab will not open the external app and will instead stay in the tab. Intent picker is never shown in a custom tab.

Therefore what I recommend you for now is to devise a custom scheme for you app and handle that url yourself. Then your app is guaranteed to be opened.
