### ISSUE TITLE
CustomTabsIntent.launchUrl should accept Context, not Activity

### ISSUE THREAD

**Issue by joshfriend** [GoogleChrome/custom-tabs-client#16]
The `launchUrl` method of `CustomTabsIntent` should accept an instance of `Context`. `ArrayAdapter` instances do not have an `Activity` reference by default, but they do have a `getContext` method which can be used to start the custom tab just fine.

I'd love to submit a fix for this myself, but PRs don't seem to be accepted to this repo (and i dont think this one is the source for the `customtabs` support library anyways), and an official contribution guideline is still missing.

**Comment by andreban** [comment]
In order to launch Custom Tabs in the same task as your application, it must be launched from inside an `Activity`. Also, if launched from other types of `Context`, the Close button may get inconsistent, as instead of taking the user back to the host application, they will be taken to whatever process they were using before launching the tab.

Inside the samples, the `NotificationParentActivity ` sample launches a CustomTab from inside the onCreate method of the host activity, correctly setting up the task and the close button.

**Comment by pasko** [comment]
FYI, we now have a process for contributing, but I don't think it is needed in this case.

Process:
https://github.com/GoogleChrome/custom-tabs-client/blob/master/CONTRIBUTING.md
